### ISSUE TITLE
NameError: name 'Collection' is not defined

### ISSUE THREAD

**Issue by heng-yin** [nestordemeure/ManifoldMixupV2#4]
Thank you for your excellent work!
I just ran the demo.py with the newest fastai. I changed  the _fastai2_ to _fastai_.
However, when I import _manifold_mixup_, there is a erros look like this:

NameError              
Traceback (most recent call last)
<ipython-input-3-bf3eb8314f0d> in <module>
      1 from fastai.vision.all import *
----> 2 from manifold_mixup import *
~/study/ManifoldMixupV2/manifold_mixup.py in <module>
     79 # Manifold Mixup
     80 
---> 81 class ManifoldMixup(Callback):
     82     "Callback that mixes a random inner layer and the target."
     83     run_after,run_valid = [Normalize],False
~/study/ManifoldMixupV2/manifold_mixup.py in ManifoldMixup()
     82     "Callback that mixes a random inner layer and the target."
     83     run_after,run_valid = [Normalize],False
---> 84     def __init__(self, alpha:float=0.4, use_input_mixup:bool=True, module_list:Collection=None):
     85         """
     86         alpha is the parameter for the beta law.
NameError: name 'Collection' is not defined

Could you help me with this?

**Comment by nestordemeure** [comment]
It sounds like the name of a type annotation was changed, it should be fairly easy to fix. I will look into it as soon as I get the time (hopefully within 48 hours).

In the meantime you can solve the problem by removing the type annotation (which is optional anyway).

**Comment by nestordemeure** [comment]
The problem is now solved, thank you for reporting it :) 
(some fastai internals changed since the last time I used this project so it needed a refresh anyway)
